---
name: Kube Monitor CI

"on":
  push:
    branches:
      - main
      - master
      - 'feature/**'

  pull_request:
    branches:
      - main
      - master

  issues:
    types: [opened, edited, reopened]

jobs:
  validate:
    name: Validate Kubernetes Deployment
    runs-on: ubuntu-latest

    steps:
      # checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # YAML Validation
      - name: Install YAML Validator
        run: |
          sudo apt-get update
          sudo apt-get install -y yamllint

      - name: Validate YAML files
        run: |
          yamllint .

      # Install kubeconform
      - name: Install kubeconform
        run: |
          KUBECONFORM_URL="https://github.com/yannh/kubeconform/releases/latest/download/"
          KUBECONFORM_FILE="kubeconform-linux-amd64.tar.gz"

          curl -L \
            "${KUBECONFORM_URL}${KUBECONFORM_FILE}" \
            -o kubeconform.tar.gz

          tar -xzf kubeconform.tar.gz
          sudo mv kubeconform /usr/local/bin/

      # Validate Kubernetes schema
      - name: Validate Kubernetes schema
        run: |
          kubeconform \
            deployment.yaml \
            service.yaml

      # Summary
      - name: Summary
        run: |
          echo "Validation Completed"
